export enum AuthReason {
  SESSION_REQUIRED = "SESSION_REQUIRED",
  INVALID_SESSION = "INVALID_SESSION",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
  NOT_TEAM_MEMBER = "NOT_TEAM_MEMBER",
}
