export enum PlayerReason {
  PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND",
  ALREADY_INVITED = "ALREADY_INVITED",
  ALREADY_MEMBER = "ALREADY_MEMBER",
  NOT_INVITED = "NOT_INVITED",
  NOT_RECIPIENT = "NOT_RECIPIENT",
  EMAIL_ALREADY_INVITED = "EMAIL_ALREADY_INVITED",
  NOT_PLAYER_OWNER = "NOT_PLAYER_OWNER",
  OWNER_CANNOT_LEAVE = "OWNER_CANNOT_LEAVE",
  NOT_TEAM_OWNER = "NOT_TEAM_OWNER",
  TARGET_NOT_IN_TEAM = "TARGET_NOT_IN_TEAM",
  TARGET_NOT_MEMBER = "TARGET_NOT_MEMBER",
}
