packages:
  - "."
  - blueprint

allowBuilds:
  "@swc/core": false
  core-js-pure: true
  esbuild: true
  mongodb-memory-server: false
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@tailwindcss/node@4.3.2"
  - "@tailwindcss/oxide-android-arm64@4.3.2"
  - "@tailwindcss/oxide-darwin-arm64@4.3.2"
  - "@tailwindcss/oxide-darwin-x64@4.3.2"
  - "@tailwindcss/oxide-freebsd-x64@4.3.2"
  - "@tailwindcss/oxide-linux-arm-gnueabihf@4.3.2"
  - "@tailwindcss/oxide-linux-arm64-gnu@4.3.2"
  - "@tailwindcss/oxide-linux-arm64-musl@4.3.2"
  - "@tailwindcss/oxide-linux-x64-gnu@4.3.2"
  - "@tailwindcss/oxide-linux-x64-musl@4.3.2"
  - "@tailwindcss/oxide-wasm32-wasi@4.3.2"
  - "@tailwindcss/oxide-win32-arm64-msvc@4.3.2"
  - "@tailwindcss/oxide-win32-x64-msvc@4.3.2"
  - "@tailwindcss/oxide@4.3.2"
  - "@tailwindcss/postcss@4.3.2"
  - tailwindcss@4.3.2
  - "@types/node@26.4.0"
  - "@better-auth/core@1.7.2"
  - "@better-auth/drizzle-adapter@1.7.2"
  - "@better-auth/kysely-adapter@1.7.2"
  - "@better-auth/memory-adapter@1.7.2"
  - "@better-auth/mongo-adapter@1.7.2"
  - "@better-auth/prisma-adapter@1.7.2"
  - "@better-auth/telemetry@1.7.2"
  - "@testing-library/react@16.3.3"
  - better-auth@1.7.2
  - chromatic@18.6.1
  - fumadocs-core@16.15.4
  - fumadocs-mdx@15.4.0
  - fumadocs-ui@16.15.4
