import { execFileSync } from "node:child_process";

// Trailers are parsed via git itself — interpret-trailers already implements
// git's last-paragraph rule and its formatting tolerance.
function parseTrailers(rawMessage) {
  const stdout = execFileSync("git", ["interpret-trailers", "--parse"], {
    input: rawMessage ?? "",
    encoding: "utf8",
  });
  const trailers = new Map();
  for (const line of stdout.split("\n")) {
    const separator = line.indexOf(": ");
    if (separator === -1) continue;
    const key = line.slice(0, separator).toLowerCase();
    const value = line.slice(separator + 2);
    const values = trailers.get(key) ?? [];
    values.push(value);
    trailers.set(key, values);
  }
  return trailers;
}

function currentBranch() {
  if (process.env.COMMITLINT_BRANCH) return process.env.COMMITLINT_BRANCH;
  try {
    return execFileSync("git", ["branch", "--show-current"], {
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

export const CHANGE_BRANCH_PREFIXES = ["feat", "fix", "refactor"];
const CHANGE_BRANCH = new RegExp(
  `^(${CHANGE_BRANCH_PREFIXES.join("|")})/(.+)$`,
);

function fixPathSuffix(prefix, slug) {
  return `Fix-path work belongs on hotfix/${slug} instead, not ${prefix}/${slug}.`;
}

export function evaluateChangeBranchTrailer(branchName, message) {
  if (!branchName) return { ok: true }; // detached HEAD (e.g. rebase reword): skip silently

  const match = branchName.match(CHANGE_BRANCH);
  if (!match) return { ok: true };
  const [, prefix, slug] = match;

  const value = parseTrailers(message).get("blueprint-change")?.[0];
  if (value === undefined) {
    return {
      ok: false,
      message: `branch "${branchName}" is a Change branch (slug "${slug}") and needs a "Blueprint-Change: ${slug}" trailer, but the commit has none. ${fixPathSuffix(prefix, slug)}`,
    };
  }
  if (value !== slug) {
    return {
      ok: false,
      message: `branch "${branchName}" needs "Blueprint-Change: ${slug}", but the commit carries "Blueprint-Change: ${value}". ${fixPathSuffix(prefix, slug)}`,
    };
  }
  return { ok: true };
}

const AI_NAMES = [
  "claude",
  "anthropic",
  "chatgpt",
  "copilot",
  "codex",
  "gemini",
];

function namesAiAssistant(text) {
  const lower = text.toLowerCase();
  return AI_NAMES.some((name) => lower.includes(name));
}

// `git commit -v` appends the diff below the scissors line; the
// commit-msg hook sees it uncut, so a "generated by" mention in the diff
// itself must not be mistaken for one in the message.
const SCISSORS = /^# -+ >8 -+$/m;

function stripDiffAndComments(rawMessage) {
  const scissors = SCISSORS.exec(rawMessage);
  const aboveScissors = scissors
    ? rawMessage.slice(0, scissors.index)
    : rawMessage;
  return execFileSync("git", ["stripspace", "--strip-comments"], {
    input: aboveScissors,
    encoding: "utf8",
  });
}

// Only attribution keys count: a Blueprint-Change slug or a Refs value
// may legitimately contain an assistant's name.
const ATTRIBUTION_TRAILERS = new Set(["co-authored-by", "generated-by"]);
// Anchored at line start (after any emoji), so prose quoting the rule passes.
const GENERATED_LINE = /^\W*generated[\s-](with|by)\b/i;

export function evaluateAiAttribution(message) {
  const raw = message ?? "";

  for (const [key, values] of parseTrailers(raw)) {
    if (!ATTRIBUTION_TRAILERS.has(key)) continue;
    const named = values.find(namesAiAssistant);
    if (named) {
      return {
        ok: false,
        message: `commit carries a "${key}" trailer naming an AI assistant ("${named}"); AI attribution is not allowed in commit messages.`,
      };
    }
  }

  const generatedLine = stripDiffAndComments(raw)
    .split("\n")
    .find((line) => GENERATED_LINE.test(line) && namesAiAssistant(line));
  if (generatedLine) {
    return {
      ok: false,
      message: `commit message names an AI assistant in a "Generated with/by" line ("${generatedLine.trim()}"); AI attribution is not allowed in commit messages.`,
    };
  }

  return { ok: true };
}

// The conventional parser starts the footer at the first line shaped like
// "Token: value". When the body opens with such a line, the whole body
// becomes footer and commitlint reports an empty body instead. Only the
// opening line is flagged: a "Verification: ..." paragraph later in a body
// is common and parses harmlessly.
const FOOTER_TOKEN = /^[A-Za-z][\w-]*: \S/;

export function evaluateFooterLookalike(message) {
  const [, ...paragraphs] = stripDiffAndComments(message ?? "")
    .trim()
    .split(/\n\s*\n/);
  // A lone paragraph after the subject is the trailer block, not a body.
  const firstLine = paragraphs.length > 1 ? paragraphs[0].split("\n")[0] : "";
  return FOOTER_TOKEN.test(firstLine)
    ? {
        ok: false,
        message: `the body opens with "${firstLine}", which reads as a footer token, so commitlint sees no body; reword it so it does not start with "${firstLine.split(":")[0]}:".`,
      }
    : { ok: true };
}

function toRuleOutcome(verdict) {
  return verdict.ok ? [true] : [false, verdict.message];
}

// The one local plugin commitlint allows per project (ADR-0055).
const plugin = {
  rules: {
    "blueprint-change-trailer": (parsed) =>
      toRuleOutcome(evaluateChangeBranchTrailer(currentBranch(), parsed.raw)),
    "no-ai-attribution": (parsed) =>
      toRuleOutcome(evaluateAiAttribution(parsed.raw)),
    "footer-lookalike": (parsed) =>
      toRuleOutcome(evaluateFooterLookalike(parsed.raw)),
  },
};

export default plugin;
