#!/usr/bin/env node
/*
 * Guards the build-facing scenarios of the pwa-service-worker spec.
 *
 * The service worker is generated by the prerendered /serwist/[path] route
 * (@serwist/turbopack). After `next build`, its response body and headers are
 * written to .next/server/app/serwist/sw.js.{body,meta}. This script asserts:
 *   1. the route metadata carries content-type application/javascript and
 *      service-worker-allowed "/" (Requirement: Service worker generated by
 *      the Next.js build);
 *   2. the precache manifest contains no navigation documents — every entry is
 *      a static asset with a file extension, never a bare route path
 *      (Requirement: Install-time precache covers static assets only);
 *   3. the manifest still contains build chunks (/_next/static) and public
 *      assets (Decision 3: only the nav shells leave the precache).
 *
 * Run after the app build; chained into verify:all so CI fails if any holds.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const META = ".next/server/app/serwist/sw.js.meta";
const BODY = ".next/server/app/serwist/sw.js.body";

let meta, body;
try {
  meta = JSON.parse(readFileSync(META, "utf8"));
  body = readFileSync(BODY, "utf8");
} catch (err) {
  console.error(
    `assert-sw: could not read the built worker (${err.message}). ` +
      "Run `next build` first.",
  );
  process.exit(1);
}

// 1. Baked headers grant root scope and identify the file as a worker.
assert.equal(
  meta.headers?.["content-type"],
  "application/javascript",
  "worker content-type must be application/javascript",
);
assert.equal(
  meta.headers?.["service-worker-allowed"],
  "/",
  'worker must be served with service-worker-allowed "/"',
);

// 2/3. Precache manifest: static assets only, no navigation documents.
const urls = [
  ...new Set([...body.matchAll(/url:\s*"([^"]+)"/g)].map((m) => m[1])),
];
assert.ok(urls.length > 0, "precache manifest is empty");

// A navigation document is an extension-less route path (e.g. "/", "/home").
// Every real precache asset ends in a file extension (.js, .png, .json, ...).
const navDocs = urls.filter((u) => !u.split("/").pop().includes("."));
assert.deepEqual(
  navDocs,
  [],
  `precache must not contain navigation documents, found: ${navDocs.join(", ")}`,
);

assert.ok(
  urls.some((u) => u.startsWith("/_next/static/")),
  "precache must contain build chunks (/_next/static)",
);
assert.ok(
  urls.some((u) => /\.(png|svg|ico|json|webmanifest)$/.test(u)),
  "precache must contain public assets",
);

console.log(
  `assert-sw: OK — headers baked, ${urls.length} precache entries, no navigation documents.`,
);
